apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "ternero.fullname" . }}
  labels:
    app: {{ include "ternero.name" . }}
    helm.sh/chart: {{ include "ternero.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "ternero.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ include "ternero.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      serviceAccountName: {{ include "ternero.name" . }}
      containers:
      - image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        name: {{ include "ternero.name" . }}
        ports:
        - containerPort: 8989
          protocol: TCP
        args:
        - "--https-listen-port=0"
        - "--http-listen-port=8989"
