apiVersion: v1
kind: Service
metadata:
  name: {{ include "ternero.fullname" . }}
  labels:
    app: {{ include "ternero.name" . }}
    helm.sh/chart: {{ include "ternero.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  type: {{ .Values.service.type }}
  ports:
  - port: {{ .Values.service.port }}
    targetPort: 8989
    protocol: TCP
    name: http
{{- if .Values.service.nodePort }}
    nodePort: {{ .Values.service.nodePort }}
{{- end }}
  selector:
    app: {{ include "ternero.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
