replicaCount: 1

image:
  repository: cnrancher/kube-explorer
  tag: ""
  pullPolicy: IfNotPresent

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

service:
  type: LoadBalancer
  port: 8989
  nodePort: ""

ingress:
  enabled: true
  annotations: {}
  paths: []
  host: []
  tls: []

resources: {}

nodeSelector: {}

tolerations: []

affinity: {}
